import { createReadStream, writeFileSync } from "node:fs";
import { createInterface } from "node:readline";
import { splitOnFirstSpace } from "./utils";

const _file_path = "./scripts/ahk-fn-wrapper.txt";
const _out_file_path = "./src-runtime/generate-out/ahk-fn-wrapper-gen.ts";

main();

async function main() {
  console.time("main");
  const fs = createReadStream(_file_path, { encoding: "utf-8" });
  const rl = createInterface({
    input: fs,
    crlfDelay: Infinity,
  });

  const res_arr: string[] = [
    "/* eslint-disable */",
    "// NOTE: The content of this file is automatically generated by a script; any content will be overwritten.",
    "import { invokeFnAsync } from \"../runtime-web\";",
  ];

  for await (const line of rl) {
    if (line.trim() === "" || line.startsWith("//")) {
      continue;
    }
    const arr: string[] = splitOnFirstSpace(line);
    if (arr.length === 1) {
      arr.push(""); // 如果没有空格，补充一个空字符串作为第二部分
    }
    const name = arr[0].trim();
    const comment = arr[1].trim();
    let item = "";
    if (name.startsWith("A_")) {
      item = `/**
 * ${comment}
 */
export function ${name}() {
    return invokeFnAsync("get_a_variable_value", "${name}");
}`;
    }
    else {
      item = `/**
 * ${comment}
 */
export function ${name}(...args: any[]) {
    return invokeFnAsync("${name}", ...args);
}`;
    }
    if (item.trim() !== "") {
      res_arr.push(item);
    }
  }

  const res = res_arr.join("\n\n");
  writeFileSync(_out_file_path, res, { encoding: "utf-8" });
  console.timeEnd("main");
}
