import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { cwd } from "node:process";
import { name } from "../package.json";
import { getFilesPath } from "./utils/index";

const _web_build_dir_name = "dist";
const _generate_file_path = "src-runtime/generate-out/assets-gen.ahk";
const _open_console_window = false;

main();

function main() {
  console.time("main");

  // 获取所有的文件路径
  const file_arr: string[] = getFilesPath(_web_build_dir_name);
  // console.log(file_arr);

  const code_arr: string[] = [
    ";NOTE: The content of this file is automatically generated by a script; any content will be overwritten.",
  ];

  const out_path = join(cwd(), "out");

  if (!existsSync(out_path)) {
    // 不存在则创建文件夹
    mkdirSync(out_path);
  }
  // 指定 exe 生成的目录, 不指定默认生成到 入口文件同级
  code_arr.push(`;@Ahk2Exe-ExeName ${join(out_path, `${name}.exe`)}`);

  // 设置是否打开控制台 (默认估计是 win32 桌面程序)
  if (_open_console_window) {
    code_arr.push(";@Ahk2Exe-ConsoleApp");
  }

  // 将所有的 前端文件 添加到嵌入的资源
  for (const item of file_arr) {
    // \\ 双斜杠 转为 \ 单斜杠
    const file_path = item.replace("\\\\", "\\");
    const target_res_path = file_path.replace(`${_web_build_dir_name}\\`, "");

    // let str = `;@Ahk2Exe-AddResource ..\\${file_path}, ${target_res_path}`
    const str = `;@Ahk2Exe-AddResource ${join(cwd(), file_path)}, ${target_res_path}`;
    code_arr.push(str);
  }
  const code = code_arr.join("\n");
  // 保存到文件
  writeFileSync(_generate_file_path, code, {
    encoding: "utf-8",
  });
  console.timeEnd("main");
}
