;NOTE: The content of this file is automatically generated by a script; any content will be overwritten.
;@Ahk2Exe-ExeName D:\Work\AutohotkeyProject\AutoHotKey-WebView2\out\autohotkey-webview2-react.exe
;@Ahk2Exe-AddResource D:\Work\AutohotkeyProject\AutoHotKey-WebView2\dist\assets\index-BJulNP-t.css, assets\index-BJulNP-t.css
;@Ahk2Exe-AddResource D:\Work\AutohotkeyProject\AutoHotKey-WebView2\dist\assets\index-CbjLwkWI.js, assets\index-CbjLwkWI.js
;@Ahk2Exe-AddResource D:\Work\AutohotkeyProject\AutoHotKey-WebView2\dist\assets\index-DjZzEGwZ.js, assets\index-DjZzEGwZ.js
;@Ahk2Exe-AddResource D:\Work\AutohotkeyProject\AutoHotKey-WebView2\dist\assets\Layout-Bp2kRdh9.js, assets\Layout-Bp2kRdh9.js
;@Ahk2Exe-AddResource D:\Work\AutohotkeyProject\AutoHotKey-WebView2\dist\assets\packages-BDNOyzxu.css, assets\packages-BDNOyzxu.css
;@Ahk2Exe-AddResource D:\Work\AutohotkeyProject\AutoHotKey-WebView2\dist\assets\packages-Cs2fokZB.js, assets\packages-Cs2fokZB.js
;@Ahk2Exe-AddResource D:\Work\AutohotkeyProject\AutoHotKey-WebView2\dist\assets\react-CHdo91hT.svg, assets\react-CHdo91hT.svg
;@Ahk2Exe-AddResource D:\Work\AutohotkeyProject\AutoHotKey-WebView2\dist\flash.gif, flash.gif
;@Ahk2Exe-AddResource D:\Work\AutohotkeyProject\AutoHotKey-WebView2\dist\index.html, index.html
;@Ahk2Exe-AddResource D:\Work\AutohotkeyProject\AutoHotKey-WebView2\dist\vite.svg, vite.svg